### ISSUE TITLE
NoMethodError: undefined method `path' for LWRP

### ISSUE THREAD

**Issue by kemra102** [nvwls/zap#29]
It seems that **zap_directory** has been broken, at least as far as it's documented usage since [this commit](https://github.com/nvwls/zap/commit/dc711756bf63bd26cd121d37a5490f0582afa1b9#diff-1dbee09fc2fd79ca90d5f08076ce92c7) and therefore v0.8.1

When running tests on my own cookbook that uses this resource I get the following error:

```bash
================================================================================
           Error executing action `delete` on resource 'zap_directory[/etc/nginx/conf.d]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `path' for LWRP resource nginx_server_block from cookbook nginx_server

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/zap/libraries/directory.rb:47:in `select'
           /tmp/kitchen/cache/cookbooks/zap/libraries/default.rb:123:in `call'
           /tmp/kitchen/cache/cookbooks/zap/libraries/default.rb:123:in `block in iterate'
           /tmp/kitchen/cache/cookbooks/zap/libraries/default.rb:122:in `iterate'
           /tmp/kitchen/cache/cookbooks/zap/libraries/default.rb:99:in `action_delete'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/nginx_server/recipes/default.rb

            24:   zap_directory '/etc/nginx/conf.d' do
            25:     klass [Chef::Resource::File, Chef::Resource::Template,
            26:            Chef::Resource::NginxServerBlock]
            27:   end
            28: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/nginx_server/recipes/default.rb:24:in `from_file'

           zap_directory("/etc/nginx/conf.d") do
             provider Chef::Provider::ZapDirectory
             action :delete
         retries 0
             retry_delay 2
             default_guard_interpreter :default
             delayed true
             pattern "*"
         klass [Chef::Resource::File, Chef::Resource::Template, LWRP resource nginx_server_block from cookbook nginx_server]
         declared_type :zap_directory
             cookbook_name "nginx_server"
         recipe_name "default"
           end


       Running handlers:
       [2015-11-16T23:43:32+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-11-16T23:43:32+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 03 seconds
       [2015-11-16T23:43:32+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2015-11-16T23:43:32+00:00] ERROR: zap_directory[/etc/nginx/conf.d] (nginx_server::default line 24) had an error: NoMethodError: undefined method `path' for LWRP resource nginx_server_block from cookbook nginx_server
       [2015-11-16T23:43:32+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Switching to v0.8.0 of the cookbook fixes this issue.

I implement **zap_directory** [here](https://github.com/kemra102/nginx_server-cookbook/blob/master/recipes/default.rb#L23-L28).

Oddly setting **path** like so:

```ruby
zap_directory 'nginx_confd' do
  klass [Chef::Resource::File, Chef::Resource::Template, Chef::Resource::NginxServerBlock]
  path '/etc/nginx/conf.d'
end
```

makes no difference and produces the exact same error.

**Comment by glenjamin** [comment]
The problem here is that selected resources must have a `path` property for the following line to work: https://github.com/nvwls/zap/blob/master/libraries/directory.rb#L52

The fix in this case is to give `nginx_server_block` a `path` property, or to create a new `zap_nginx_site` which can handle more types of resource.

**Comment by nvwls** [comment]
In v0.10.1, we check that the resource responds to `:path` before calling `path`
